# sample spacemesh config file
# use the config flag to start a node with a config file.
# e.g $./go-spacemesh --config ./config.toml
# cli flags will get a higher priority than configured in the file.

# Main Config
[main]
data-folder = "~/.spacemesh-data"
metrics = false
metrics-port = 2020
oracle_server = "http://localhost:3030"
oracle_server_worldid = 0
genesis-time = "2019-02-13T17:02:00+00:00"
layer-duration-sec = "5"
golden-atx = "0x5678"

[tortoise]
tortoise-hdist = "5"

[smeshing]
smeshing-coinbase = "0x1234"

# Node Config
[p2p]
network-id = 1 # 0 - MainNet, 1 - TestNet

[p2p.bootstrap]
target-outbound = 10

[p2p.discovery]
bootnodes = [] # example : spacemesh://j7qWfWaJRVp25ZsnCu9rJ4PmhigZBtesB4YmQHqqPvt@0.0.0.0:7517?disc=7517

# API Config
[api]
grpc = "node" # Only run the Node service by default
json-server = true
grpc-port = 9092
json-port = 9093

# Hare Config
[hare]
hare-round-duration-sec = "5"
hare-committee-size = 800
hare-max-adversaries = 399
hare-wakeup-delta = 5

# Beacon Config
[beacon]
beacon-kappa = 40
beacon-q = "1/3"
beacon-rounds-number = 300
beacon-grace-period-duration = "2m"
beacon-proposal-duration = "2m"
beacon-first-voting-round-duration = "1h"
beacon-voting-round-duration = "30m"
beacon-weak-coin-round-duration = "1m"
beacon-theta = "1/4"
beacon-votes-limit = 100
beacon-sync-num-blocks = 1600

[logging]
log-encoder = "console"
app = "info"
p2p = "info"
post = "info"
stateDb = "info"
state = "info"
store = "info"
poetDb = "info"
meshDb = "info"
trtl = "info"
atxDb = "info"
block-eligibility = "info"
mesh = "info"
sync = "info"
block-oracle = "info"
hare-oracle = "info"
hare = "info"
block-builder = "info"
block-listener = "info"
poet = "info"
nipost = "info"
atx-builder = "info"
hare-beacon = "info"
beacon = "info"
weakCoin = "info"
